version: "2"
services:
  client:
    container_name: exertracker_client
    restart: always
    build: client
    ports:
      - "3000:3000"
    links:
        - server
  server:
    container_name: exertracker_server
    restart: always
    build: server
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: exertracker_mongo
    image: mongo
    ports:
      - "27017:27017"