version: "2"
services:
  server:
    container_name: exertracker_server
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: exertracker_mongo
    image: mongo
    ports:
      - "27017:27017"